services:
  backend:
    build:
      context: ./backend
    container_name: backend-health-api
    ports:
      - "4000:4000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: react-docker-app
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
